language: python

python:
  - 3.6

services:
  - postgresql

env:
  global:
    - "STATE"="Testing"

before script:
  - psql -c "CREATE DATABASE ireportertest;" -U postgres
  - export DATABASE ireportertest

install:
  - pip install -r requirements.txt

script:
  - pytest --cov

after_success:
  - coveralls
