language: python

python:
  - 3.6

services:
  - postgresql

before script:
  - psql -c "CREATE DATABASE ireportertest;" -U postgres

install:
  - pip install -r requirements.txt

script:
  - pytest --cov

after_success:
  - coveralls
