language: python

python:
  - 3.6

services:
  - postgresql

install:
  - pip install -r requirements.txt

before script:
  - psql -c "CREATE DATABASE 'ireportertest';" -U postgres

script:
  - pytest --cov=api --cov-report term-missing

after_success:
  - coveralls
