language: python

python:
  - 3.6

services:
  - postgresql

env:
  global:
    - STATE = "Testing"

before script:
  - psql -c "CREATE DATABASE 'ireportertest';" -U postgres

install:
  - pip install -r requirements.txt

script:
  - pytest --cov=api --cov-report term-missing

after_success:
  - coveralls
